### ISSUE TITLE
Update requirements.txt and also fix the issue with the file

### ISSUE THREAD

**Issue by AmitMourya1322** [anirudhpnbb/Pyostie#46]
**Describe the bug**
not working

need to install lots of module manually

**Additional context**
![fvdfv](https://user-images.githubusercontent.com/30823625/118856962-23ad7280-b8f5-11eb-8f62-d33cbf8f5b8f.JPG)

**Comment by anirudhpnbb** [comment]
Hello @AmitMourya1322. Thanks for bringing this to our notice. We are trying our best to resolve this. For us to proceed and understand your problem even better, can you please share the file that you're trying to process here ?

**Comment by AmitMourya1322** [comment]
tried these 2 files

**Comment by anirudhpnbb** [comment]
@AmitMourya1322 I can't find any files attached. Please check and revert

**Comment by anirudhpnbb** [comment]
@AmitMourya1322  I can't find any files attached. Please share the files.

**Comment by AmitMourya1322** [comment]
these 2 pics i have used

>

**Comment by anirudhpnbb** [comment]
Hello please verify. Pyostie 2.5.4 fixes this error.

**Comment by anirudhpnbb** [comment]
Closing this error for now.  Even if the error repeats, please reopen the issue.
